<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Website</name>
   <tag></tag>
   <elementGuidId>a7300f29-03d4-487d-b3aa-0d9ca22743d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>figcaption > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[3]/div/figure/figcaption/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f50bc37-8426-4241-8852-6423aeea12f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/CourseStatus.awp?&amp;Course=cedhom</value>
      <webElementGuid>36cadfb3-6554-4a49-a3a2-1830b07dacd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>8ac07641-09d7-4891-9bac-c2eeda4b2b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>8edf4273-c47d-45e6-b02a-b1aef1735488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 col-lg-4 text-center&quot;]/figure[1]/figcaption[1]/a[1]</value>
      <webElementGuid>5251cc42-2147-45c7-993b-780085267001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[3]/div/figure/figcaption/a</value>
      <webElementGuid>ffc7a9da-4142-4405-9efe-8b739cb1ce77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Website')]</value>
      <webElementGuid>ead9c695-b279-4b13-8bc8-7e62d4324447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalogs'])[1]/following::a[2]</value>
      <webElementGuid>048ff3bf-625e-41a9-a7be-0e4bfa98b684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PDF'])[1]/preceding::a[1]</value>
      <webElementGuid>496af2d8-494e-45ea-8c27-886bf4205fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Website']/parent::*</value>
      <webElementGuid>7a472112-2b5a-4ab2-a410-f335cfb85cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wconnect/CourseStatus.awp?&amp;Course=cedhom')])[5]</value>
      <webElementGuid>54517aa2-ab45-4595-862a-01c6c2f1924e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figcaption/a</value>
      <webElementGuid>a79dc4fb-9395-4d0c-9ed8-70b246eb04a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/CourseStatus.awp?&amp;Course=cedhom' and (text() = 'Website' or . = 'Website')]</value>
      <webElementGuid>e8d83272-c354-47d8-bdf7-d57f18a7b097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
