<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Website_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>98fe8b52-a1cf-4c36-a821-e0d288e1b377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[4]/div/figure/figcaption/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>46005ddb-aabe-4439-ab65-f66e2051fbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/SubGroup.awp?~~CER</value>
      <webElementGuid>2d0c926d-49df-4b98-90e3-7fca5941fe9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>8c7cd821-ed31-4474-a22d-82327f96a1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>ff481141-9a19-4895-bb42-378e73b645ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 col-lg-4 text-center&quot;]/figure[1]/figcaption[1]/a[1]</value>
      <webElementGuid>c525190b-7fa3-48de-8b15-034b0723b9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[4]/div/figure/figcaption/a</value>
      <webElementGuid>f5be8de9-470d-4781-851c-c2dd63ea245f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Website')])[4]</value>
      <webElementGuid>d5cd9173-07b8-4e57-9c76-fd2568760a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PDF'])[3]/following::a[2]</value>
      <webElementGuid>c6d42aaa-73cd-40f7-a168-c09e53624bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PDF'])[4]/preceding::a[1]</value>
      <webElementGuid>200ba9b3-4990-45b4-b056-e164b9805728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wconnect/SubGroup.awp?~~CER')]</value>
      <webElementGuid>7197a9d1-27d8-40b9-b598-fbf605449885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/figure/figcaption/a</value>
      <webElementGuid>9e4398ca-429d-47a2-925f-b4a3c1917122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/SubGroup.awp?~~CER' and (text() = 'Website' or . = 'Website')]</value>
      <webElementGuid>cb9200b2-b14d-4b48-9e64-4db6b99512d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
