<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Website_1</name>
   <tag></tag>
   <elementGuidId>cf9ca6e6-6ddf-4c2d-92e9-f388647d8ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[3]/div[2]/figure/figcaption/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>989d0469-3fcc-4e8b-a016-41687a23dd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/CourseStatus.awp?&amp;Course=oshhom</value>
      <webElementGuid>5105e528-fbde-466e-bcdf-a96c9aa97fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>1eab239f-41bf-45bf-9237-d6f044631947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>a7bf5d85-a0ef-43b4-814d-5dc10f951cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 col-lg-4 text-center&quot;]/figure[1]/figcaption[1]/a[1]</value>
      <webElementGuid>ca2ec282-09cc-4f94-a8bf-0eb8ae719ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[3]/div[2]/figure/figcaption/a</value>
      <webElementGuid>318a29a6-383a-4fa9-93d3-9d9bdfb7249e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Website')])[2]</value>
      <webElementGuid>d40c6d6e-5127-4df2-853a-f11cfc6a0f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PDF'])[1]/following::a[2]</value>
      <webElementGuid>ea1bb2e1-1224-41af-80fc-7b755f339b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PDF'])[2]/preceding::a[1]</value>
      <webElementGuid>5c6aaf97-b4fd-4cea-9828-4b68d9bfc0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wconnect/CourseStatus.awp?&amp;Course=oshhom')]</value>
      <webElementGuid>ff6b3dcb-a1a4-462a-ae74-3e94817e1d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/figure/figcaption/a</value>
      <webElementGuid>16a75123-0a3a-4b8a-9d97-3cb373a40016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/CourseStatus.awp?&amp;Course=oshhom' and (text() = 'Website' or . = 'Website')]</value>
      <webElementGuid>d06e432f-d3e6-4b5e-b8b9-e15a12005a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
