<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download PDF_cat-img_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>90dffa31-4779-42c3-a415-06ce7efd0db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[5]/div/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f806184b-378d-49fa-9c24-a40d200f98fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cat-img</value>
      <webElementGuid>ac03d7ad-ee08-4682-8c38-6ed34655ab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cedwebfiles/catalogs/2024/2024 SH Fall Catalog - Spanish - Thumbnail.jpg</value>
      <webElementGuid>85b92466-cbfd-4b03-97f3-932fe80a0991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>S&amp;H Spanish Catalog 2024 cover</value>
      <webElementGuid>280118c1-f96c-442b-892b-8f6597fe7a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>390px</value>
      <webElementGuid>ce5f5c02-31e9-4a5a-b50b-5788d5d4fd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>b518d9fc-ba51-4634-b968-f69f31c9b8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 col-lg-4 text-center&quot;]/figure[1]/a[1]/img[@class=&quot;cat-img&quot;]</value>
      <webElementGuid>a185586e-915e-487e-8ea3-9163dee1b390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[5]/div/figure/a/img</value>
      <webElementGuid>d4b32b76-9f5f-4420-a8ae-664b0ba384e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='S&amp;H Spanish Catalog 2024 cover']</value>
      <webElementGuid>11845203-662c-4b72-a3fa-33cd3bcffd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/figure/a/img</value>
      <webElementGuid>5d819d6c-b889-4cca-b83c-27ab174239ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/cedwebfiles/catalogs/2024/2024 SH Fall Catalog - Spanish - Thumbnail.jpg' and @alt = 'S&amp;H Spanish Catalog 2024 cover']</value>
      <webElementGuid>734ca3b5-c332-4ebc-b8bf-72fd1b1b2acb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
