<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Catalogs_S H Spanish Catalog 2024 cover</name>
   <tag></tag>
   <elementGuidId>90dffa31-4779-42c3-a415-06ce7efd0db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[5]/div/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5c764e08-97d7-4f95-b077-c9ff526eb84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cat-img</value>
      <webElementGuid>4eb86ec3-cb37-486d-8d99-443d92466da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cedwebfiles/catalogs/2024/2024 SH Fall Catalog - Spanish - Thumbnail.jpg</value>
      <webElementGuid>f04d82d3-0d32-4376-870f-e9cd9d057c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>S&amp;H Spanish Catalog 2024 cover</value>
      <webElementGuid>6dccab38-7f54-4189-9b75-0a9d7f73b56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>390px</value>
      <webElementGuid>83fa3dcc-1eb0-4013-90e2-17e3ae6b5d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>651283cf-612e-4c79-baef-92a11b1c1b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 col-lg-4 text-center&quot;]/figure[1]/a[1]/img[@class=&quot;cat-img&quot;]</value>
      <webElementGuid>8082613c-d307-42d0-a707-08afc90ec0ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[5]/div/figure/a/img</value>
      <webElementGuid>6896d958-fe65-4909-9adb-ee994707b970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='S&amp;H Spanish Catalog 2024 cover']</value>
      <webElementGuid>f11980a4-309b-4c01-86b1-0bde318fb23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/figure/a/img</value>
      <webElementGuid>f2b00508-af35-4cdb-8bc0-bf758a4b6593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@class = 'cat-img' and @src = '/cedwebfiles/catalogs/2024/2024 SH Fall Catalog - Spanish - Thumbnail.jpg' and @alt = 'S&amp;H Spanish Catalog 2024 cover']</value>
      <webElementGuid>89fe7a80-555a-49d7-a213-fbabde14206b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
