<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Online Training</name>
   <tag></tag>
   <elementGuidId>de303a44-d9a3-4a5e-9a41-1037fc974e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(4) > a.btn.btn-lg.btn-block.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div/div[4]/div/article/p[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d0ef1ba-539e-4279-9fc8-fb75e460d88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/ShowSchedule.awp1?&amp;Mode=GROUP&amp;Group=ONLSH</value>
      <webElementGuid>afb1b1de-b42f-47d0-a0de-521fde923be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>63de552a-90de-430d-8a63-46b064f6dff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-block btn-primary</value>
      <webElementGuid>3cf408bf-c5e2-41de-96e7-2ea86ac1744c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4899b73c-55db-46e9-baff-d3cb9461c9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Online Training</value>
      <webElementGuid>b3a15a67-5b77-485f-8ae1-4e9addb55628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Online Training</value>
      <webElementGuid>dd7f07b7-4990-4f65-b8b3-9dc0c2430103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-12 col-sm-12 col-xs-12&quot;]/article[@class=&quot;smArticles&quot;]/p[4]/a[@class=&quot;btn btn-lg btn-block btn-primary&quot;]</value>
      <webElementGuid>8f6291b3-13ad-41ce-b29e-97db5be5171e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div[4]/div/article/p[4]/a</value>
      <webElementGuid>ea1bbf86-b075-4a2a-908c-a99eba82fad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Online Training')]</value>
      <webElementGuid>35f67d99-6bd3-4382-90c6-686d64b19d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evening/Saturday Classes'])[1]/following::a[1]</value>
      <webElementGuid>e27567fd-540a-475a-b8ca-dcbb011402d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Webcasts'])[1]/following::a[2]</value>
      <webElementGuid>584feeb2-d3e4-4d0a-8715-71c309c923c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spanish Classes'])[1]/preceding::a[1]</value>
      <webElementGuid>cf15e5a3-5d02-415a-b0e2-6140c9990f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Training'])[1]/preceding::a[2]</value>
      <webElementGuid>156d0777-9c88-41a2-adc7-8a5ec62d0ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Online Training']/parent::*</value>
      <webElementGuid>1156dee1-b58f-4cc4-84e8-2d40f65c6074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wconnect/ShowSchedule.awp1?&amp;Mode=GROUP&amp;Group=ONLSH')]</value>
      <webElementGuid>23c3007f-24c5-42a3-848e-c66da9d530fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>a7116735-016e-4a2e-b458-200ca68c9b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/ShowSchedule.awp1?&amp;Mode=GROUP&amp;Group=ONLSH' and (text() = 'Online Training' or . = 'Online Training')]</value>
      <webElementGuid>d275f2a6-907c-4cca-974d-3260b8fd22ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
