<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_English_mainimg</name>
   <tag></tag>
   <elementGuidId>3575c21f-e7eb-45a7-a522-4d75f915238a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div/div[4]/div[2]/div/div[2]/article/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>175acf90-ac4a-44d6-8446-40df86c81087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mainimg</value>
      <webElementGuid>1295e841-8fc1-4e5b-9b93-3a56948a39df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cedwebfiles/catalogs/2024/2024 SH Fall Catalog - Spanish - Thumbnail.jpg</value>
      <webElementGuid>ebe01282-5b9c-4bcc-a023-4cb07c46bab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fe608340-ad6c-4df8-a5d3-dbf96bd27029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Safety &amp; Health Spanish Catalog cover</value>
      <webElementGuid>adff6dc6-69de-43b3-9398-e85e47f54bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>987ca0ca-9e59-481b-86e7-bdc388cbf68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>801dc266-81b7-49ec-8d84-e1b1a31f395d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-6 col-xs-12 text-center&quot;]/article[1]/a[1]/img[@class=&quot;mainimg&quot;]</value>
      <webElementGuid>02ddd1a8-8753-4411-bcb0-895e89435436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div[4]/div[2]/div/div[2]/article/a/img</value>
      <webElementGuid>dfad70ec-b017-402b-a615-4e212f173a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Safety &amp; Health Spanish Catalog cover']</value>
      <webElementGuid>1fea4d6d-a8b0-4a7a-b966-07951b1619d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/a/img</value>
      <webElementGuid>b347aaa2-dc3b-40e8-8888-4fccf80a32cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/cedwebfiles/catalogs/2024/2024 SH Fall Catalog - Spanish - Thumbnail.jpg' and @alt = 'Safety &amp; Health Spanish Catalog cover']</value>
      <webElementGuid>45f132f7-b001-4472-8b0b-55653e57c81d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
