<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_(817) 272-2581</name>
   <tag></tag>
   <elementGuidId>b23c2e8f-ab35-4dad-8b34-36a36ea9608b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='secondary_footer']/div[2]/div/p/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.footerfont > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ae9f00a-563b-4541-8a19-af006011bafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>tel:817-272-2581</value>
      <webElementGuid>f7ba21ad-b74e-4780-b37c-5a1fa7512b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>(817) 272-2581</value>
      <webElementGuid>b8427d81-3974-4727-b850-2859b0698735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(817) 272-2581</value>
      <webElementGuid>7f1ff412-75a2-43da-8fd6-547ec875d1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_footer&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;center&quot;]/p[@class=&quot;footerfont&quot;]/a[2]</value>
      <webElementGuid>26599aa6-aa2a-43ed-9a10-b71af9365b0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondary_footer']/div[2]/div/p/a[2]</value>
      <webElementGuid>0db583d2-166f-49bf-8975-5e1d3840dfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'(817) 272-2581')]</value>
      <webElementGuid>2f8d3330-c3de-4b62-aa2c-32d301e05814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIVISION FOR ENTERPRISE DEVELOPMENT'])[1]/following::a[2]</value>
      <webElementGuid>7be92c5b-d039-40c5-bcc0-a3d15bda2c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTENSION AND EXTENDED CAMPUS'])[1]/following::a[2]</value>
      <webElementGuid>35ce2683-a109-4c75-8453-720e77ca0198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(817) 272-2556'])[1]/preceding::a[2]</value>
      <webElementGuid>95b880f5-15a5-492e-a161-9ca30e9db908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CEDQUESTIONS@UTA.EDU'])[1]/preceding::a[3]</value>
      <webElementGuid>86c12bfc-604f-486f-bb40-683ace0b9b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(817) 272-2581']/parent::*</value>
      <webElementGuid>3f0435b2-d29a-411f-acf3-5d6699a6033a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'tel:817-272-2581')]</value>
      <webElementGuid>c7530048-dbe5-4d82-bc4c-3a0836cbcffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/p/a[2]</value>
      <webElementGuid>d105289e-4c88-4e90-98a4-b6b195499c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'tel:817-272-2581' and (text() = '(817) 272-2581' or . = '(817) 272-2581')]</value>
      <webElementGuid>7a0fe7f4-de4b-4a01-8700-2e562508efac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
