<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CEDQUESTIONSUTA.EDU</name>
   <tag></tag>
   <elementGuidId>e3ae14c1-fb92-46da-a95d-45dd718f31d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='secondary_footer']/div[2]/div/p/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6839d6c5-d934-499a-aa92-acfae12786ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:cedquestions@uta.edu</value>
      <webElementGuid>c81be093-0afc-4edf-9d45-698bb48d0efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>cedquestions@uta.edu</value>
      <webElementGuid>4dad04d5-005b-49c7-b249-bca4bc5a90ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CEDQUESTIONS@UTA.EDU</value>
      <webElementGuid>f3e6dc3c-4d42-4750-8880-31e67daaeeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_footer&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;center&quot;]/p[@class=&quot;footerfont&quot;]/a[5]</value>
      <webElementGuid>3ab73155-ae3b-43de-8879-b5f9c8bcfd2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondary_footer']/div[2]/div/p/a[5]</value>
      <webElementGuid>73af32f1-4fce-4fc6-9398-aa7c0c2d57c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CEDQUESTIONS@UTA.EDU')]</value>
      <webElementGuid>e1b032ef-9926-41c8-99fd-792860ca1cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(817) 272-2556'])[1]/following::a[1]</value>
      <webElementGuid>fa41f441-79b6-4d49-b519-e014e5e8c799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(817) 272-2581'])[1]/following::a[3]</value>
      <webElementGuid>cb6f2e6d-8ada-49cf-b5c2-4e11e5457414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal &amp; Privacy'])[1]/preceding::a[2]</value>
      <webElementGuid>32f26d2d-e195-4643-b0e4-761b3d1c24b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Policies'])[1]/preceding::a[3]</value>
      <webElementGuid>24086d9f-e8de-492d-92bc-adc1fa789fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CEDQUESTIONS@UTA.EDU']/parent::*</value>
      <webElementGuid>81d93b84-8fec-40b0-84e9-1e1eb4f5c9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:cedquestions@uta.edu')]</value>
      <webElementGuid>b35fe899-87fc-4646-ad66-1dabfa560a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>6c26c75b-f90d-4def-b6cf-028602dc70a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:cedquestions@uta.edu' and (text() = 'CEDQUESTIONS@UTA.EDU' or . = 'CEDQUESTIONS@UTA.EDU')]</value>
      <webElementGuid>c47c16f7-5a9e-460d-acb8-0c67389ff480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
