<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTACT</name>
   <tag></tag>
   <elementGuidId>7a493038-09fc-406a-a4e7-0f2aed5dd50e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='nav-menu-item-10650']/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-link.main-menu-link.hover_selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f474f3ab-d51f-4854-8b53-4e40e38ae964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/ace/contact_us.aspx</value>
      <webElementGuid>b4c4b957-dede-4207-ad0c-b6dd8e72dd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link main-menu-link hover_selected</value>
      <webElementGuid>945e520a-8b88-471f-8349-2c13becada13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>6a521d71-c1bc-4e93-af0c-8981babd987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTACT</value>
      <webElementGuid>bf91f15f-4e16-40a5-b36a-3e8f9b2e2096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;navbar navbar-default navbar-fixed-top style1  header-full-width light&quot;]/div[@class=&quot;nav-container&quot;]/div[@class=&quot;navbar-collapse collapse&quot;]/ul[@id=&quot;menu-main-menu-1&quot;]/li[@id=&quot;nav-menu-item-10650&quot;]/a[@class=&quot;menu-link main-menu-link hover_selected&quot;]</value>
      <webElementGuid>5e21904e-3b33-4f6f-8fba-08068934d81f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='nav-menu-item-10650']/a)[2]</value>
      <webElementGuid>ec343970-2875-486b-b5d2-f51a1c47f89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CONTACT')])[2]</value>
      <webElementGuid>542fd9a7-8cf7-48c6-b41b-7eb7a85de68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE COURSES'])[2]/following::a[1]</value>
      <webElementGuid>c14fc7ff-fee3-4c0d-a9c3-b6f625ee63e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERTIFICATIONS'])[2]/following::a[2]</value>
      <webElementGuid>f8693770-0c91-4a61-9375-868545d365f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[2]/preceding::a[1]</value>
      <webElementGuid>e4620252-a21d-41a1-8231-0b72826536c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CART'])[2]/preceding::a[5]</value>
      <webElementGuid>1bbfdfc1-c61b-4110-bbe1-5a785107c0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wconnect/ace/contact_us.aspx')])[2]</value>
      <webElementGuid>f1374fa1-e9c3-4fce-8443-7c8ebef239ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[5]/a</value>
      <webElementGuid>bca824e7-8aaf-4b87-a42c-7e77745519ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/ace/contact_us.aspx' and (text() = 'CONTACT' or . = 'CONTACT')]</value>
      <webElementGuid>920d2887-bc6a-4440-b6a6-87e261db364a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
