<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ENVIRONMENTAL</name>
   <tag></tag>
   <elementGuidId>e5481117-f46e-4113-b0ff-3e18decf2761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-10564']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-10564 > a.menu-link.sub-menu-link.outsider.outsider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf6c8658-e0f6-49f4-a50f-75b58db5860f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link sub-menu-link outsider outsider</value>
      <webElementGuid>3df9d2b7-6ca0-472d-955c-072cb38f1a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/CourseStatus.awp?&amp;Course=etihom</value>
      <webElementGuid>f666b364-c921-497f-9cde-d9efa584bfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Environmental</value>
      <webElementGuid>3fcb891c-9424-467c-bc68-c723c77a63f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENVIRONMENTAL</value>
      <webElementGuid>b560e1cb-094d-4be5-a8ba-9e68f375174e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-10564&quot;)/a[@class=&quot;menu-link sub-menu-link outsider outsider&quot;]</value>
      <webElementGuid>63234bbc-7a73-450c-bc4c-c146898e2440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-10564']/a</value>
      <webElementGuid>154984cd-79d9-48cd-ad5a-96c12c92ee54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ENVIRONMENTAL')])[3]</value>
      <webElementGuid>4fa6d7f1-dc31-432a-a000-38e6f703911d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuing Education'])[2]/following::a[1]</value>
      <webElementGuid>f347d103-76a1-40c5-8da4-8fbcb8e59dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[1]/following::a[4]</value>
      <webElementGuid>501cd8dd-b7d8-4a3c-9985-99d00d8f9971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEALTHCARE'])[2]/preceding::a[1]</value>
      <webElementGuid>8bb6558f-3b5a-4695-97ac-db66deeaeb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIDS &amp; TEENS UNIVERSITY'])[2]/preceding::a[3]</value>
      <webElementGuid>25c96deb-ccb0-47b9-923e-3443c9b8d21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wconnect/CourseStatus.awp?&amp;Course=etihom')])[2]</value>
      <webElementGuid>dc59957a-0b40-4929-a2ce-59bac744242d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[2]/a</value>
      <webElementGuid>1b71f35c-98ba-40d9-96d4-b34989c39f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/CourseStatus.awp?&amp;Course=etihom' and (text() = 'ENVIRONMENTAL' or . = 'ENVIRONMENTAL')]</value>
      <webElementGuid>5dc3f658-f631-4726-b0e3-17c8c9621e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
