<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HEALTHCARE</name>
   <tag></tag>
   <elementGuidId>23e2f61f-8ecf-4a97-9fb4-453f71eeb5ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-10561']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-10561 > a.menu-link.sub-menu-link.outsider.outsider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97e75bcb-a236-44f2-acc5-7b990661d55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link sub-menu-link outsider outsider</value>
      <webElementGuid>cff6d11d-2ed0-46e1-9784-f3210cb52164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/CourseStatus.awp?&amp;Course=heahom</value>
      <webElementGuid>db2afaa9-668f-4abd-b0aa-d1df49b986d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Healthcare</value>
      <webElementGuid>20cbd33b-09dd-406c-8b07-f8d7c4f7ab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HEALTHCARE</value>
      <webElementGuid>ae501ebb-c72d-4d42-bea1-710cd7dc7428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-10561&quot;)/a[@class=&quot;menu-link sub-menu-link outsider outsider&quot;]</value>
      <webElementGuid>dc07317e-ab2c-423e-b058-b552b79802ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-10561']/a</value>
      <webElementGuid>f5ae89be-b5cd-4421-b0b3-ed5766ef5b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'HEALTHCARE')])[2]</value>
      <webElementGuid>8a2777a3-1e4a-42cd-a654-4cc6ea53c592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIRONMENTAL'])[2]/following::a[1]</value>
      <webElementGuid>dff09fa5-2ad1-411c-a5d9-dda38df2ebec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuing Education'])[2]/following::a[2]</value>
      <webElementGuid>67272840-0c12-43fb-8ac3-5163c7dd7f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIDS &amp; TEENS UNIVERSITY'])[2]/preceding::a[2]</value>
      <webElementGuid>195af349-a483-4361-b800-0fc49140daa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MILITARY'])[2]/preceding::a[3]</value>
      <webElementGuid>d702daa6-5183-4e10-a449-dbc2df1342cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wconnect/CourseStatus.awp?&amp;Course=heahom')])[2]</value>
      <webElementGuid>970a9d41-6a9f-4b9e-92d0-9c856bc4d2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[3]/a</value>
      <webElementGuid>fa784018-a706-4457-ad9c-61c998ab3ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/CourseStatus.awp?&amp;Course=heahom' and (text() = 'HEALTHCARE' or . = 'HEALTHCARE')]</value>
      <webElementGuid>01bd1383-5733-4d4a-b715-963e255060e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
