<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LOGIN</name>
   <tag></tag>
   <elementGuidId>53c2fe53-7ce2-4c25-876f-d7ac445220f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='nav-menu-item-10650']/a)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-link.main-menu-link.hover_selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ab0ec72-364e-4e10-ab00-785bed755330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/ace/login.aspx</value>
      <webElementGuid>9d61f6e8-914f-4f5e-8133-6e1eb194c350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link main-menu-link hover_selected</value>
      <webElementGuid>9f6e1a52-c438-4c65-a861-1443f7926599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4b83cd94-2fba-4ee2-87ca-90b9cf727ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>95066c92-26c0-441c-a918-50317558aad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;navbar navbar-default navbar-fixed-top style1  header-full-width light&quot;]/div[@class=&quot;nav-container&quot;]/div[@class=&quot;navbar-collapse collapse&quot;]/ul[@id=&quot;menu-main-menu-1&quot;]/li[@id=&quot;nav-menu-item-10650&quot;]/a[@class=&quot;menu-link main-menu-link hover_selected&quot;]</value>
      <webElementGuid>abf60bff-2df2-4471-88d8-827ed9ba8e5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='nav-menu-item-10650']/a)[3]</value>
      <webElementGuid>694b5259-4198-444a-ac42-18fe4a37b539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'LOGIN')])[2]</value>
      <webElementGuid>ba7674e2-0c8a-4f01-974b-065d6946d37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT'])[2]/following::a[1]</value>
      <webElementGuid>0e95acf8-2756-4127-8d01-4228b70f9992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE COURSES'])[2]/following::a[2]</value>
      <webElementGuid>f3db4bb8-24cf-4777-bd40-f58b70fd47f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CART'])[2]/preceding::a[4]</value>
      <webElementGuid>03684680-4a22-4864-b4dc-e2a936c17b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuing Education'])[3]/preceding::a[6]</value>
      <webElementGuid>20202ff4-874c-4f9f-bdad-50c906d8296e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wconnect/ace/login.aspx')])[2]</value>
      <webElementGuid>bd8c182b-1c80-4506-808d-4b1774ec58cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[6]/a</value>
      <webElementGuid>0745c768-3d4a-4fa6-9281-7422e3bc4c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/ace/login.aspx' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>255e09f2-ae3e-4328-99f6-8729848818a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
