<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MILITARY</name>
   <tag></tag>
   <elementGuidId>5ed9615d-ac9d-4039-93f9-5ffcef0e9f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-10572']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-10572 > a.menu-link.sub-menu-link.outsider.outsider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a1968c1-889d-4cfa-9f24-66421824f9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link sub-menu-link outsider outsider</value>
      <webElementGuid>f6110da8-b942-477f-92e1-8a07f83ff5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wconnect/CourseStatus.awp?&amp;Course=milhom</value>
      <webElementGuid>7dba236d-306d-403c-8da0-c471211b4708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Military</value>
      <webElementGuid>7aed52d4-6df3-45b2-b055-b9e59e7648ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MILITARY</value>
      <webElementGuid>eb832319-bf24-4345-944a-40871e1a6888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-10572&quot;)/a[@class=&quot;menu-link sub-menu-link outsider outsider&quot;]</value>
      <webElementGuid>3e70e213-4846-430e-b473-d4372c7a4518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-10572']/a</value>
      <webElementGuid>94933010-c728-4fa6-8499-23d0718715d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'MILITARY')])[2]</value>
      <webElementGuid>f1bc6304-d907-439b-b2e2-73f9c08be32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIDS &amp; TEENS UNIVERSITY'])[2]/following::a[1]</value>
      <webElementGuid>dbdbe162-d9a3-4106-a688-bee4c08437c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEALTHCARE'])[2]/following::a[3]</value>
      <webElementGuid>dc535c37-3aa4-4ad0-9f78-76c41d43900a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC WORKS INSTITUTE'])[2]/preceding::a[2]</value>
      <webElementGuid>9dad709d-cb52-4c3c-befb-9292557b7116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY &amp; HEALTH'])[2]/preceding::a[3]</value>
      <webElementGuid>d788ae8d-9bd4-409c-9f7b-0eff867bcfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wconnect/CourseStatus.awp?&amp;Course=milhom')])[2]</value>
      <webElementGuid>b593472d-0c9c-40b5-ad68-6ce1d62ada24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>1a861470-70d4-41ff-9da2-74e5857be0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wconnect/CourseStatus.awp?&amp;Course=milhom' and (text() = 'MILITARY' or . = 'MILITARY')]</value>
      <webElementGuid>138341f9-4cb6-4498-bc37-735e2259519a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
