<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SERVICES</name>
   <tag></tag>
   <elementGuidId>9447aa2d-8660-4bfa-980d-4932aa39e484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-10540']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-link.main-menu-link.hover_selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbeae4de-6cfd-4ffe-8f5d-4eaaaa296e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>18043573-28fb-4e6e-ad70-c3f5f2b7bcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link main-menu-link hover_selected</value>
      <webElementGuid>dd69fe70-3eae-4707-bb25-6827f74556e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SERVICES</value>
      <webElementGuid>b82bfd08-3ca0-4959-a722-8bd0843add30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-10540&quot;)/a[@class=&quot;menu-link main-menu-link hover_selected&quot;]</value>
      <webElementGuid>f9c59d2e-12d9-41c5-a136-0ccb2092688e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-10540']/a</value>
      <webElementGuid>34bb688c-20c7-4717-b639-bea6e13dfa29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SERVICES')])[2]</value>
      <webElementGuid>dce57618-dbc8-4b03-a924-66abd34f091c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY &amp; HEALTH'])[2]/following::a[1]</value>
      <webElementGuid>e86a84a5-6185-4c33-af8f-22e73271917d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLIC WORKS INSTITUTE'])[2]/following::a[2]</value>
      <webElementGuid>12665151-9e59-49cf-b7a2-5caf6d774fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CENTER FOR ENVIRONMENTAL EXCELLENCE'])[2]/preceding::a[1]</value>
      <webElementGuid>d9169d48-d29d-4beb-a764-ef2d61fdd60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFERENCE &amp; EVENT MANAGEMENT'])[2]/preceding::a[2]</value>
      <webElementGuid>4c9b3546-6f6d-4ff9-bea5-543e4e222a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>d1515224-c47f-42ca-bd5b-3b351ed5c02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a</value>
      <webElementGuid>9e0b7a87-ae97-4286-90de-348458aa0494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'SERVICES' or . = 'SERVICES')]</value>
      <webElementGuid>a6b7ed87-2b2c-48a2-bdb8-aad584fb8ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
