<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CART_ion-grid</name>
   <tag></tag>
   <elementGuidId>fc705d20-b785-4844-a911-2029fea658fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div/div[2]/div[4]/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ion-grid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>65dbc889-fe5c-4e0c-92f2-a9673c8fdf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-grid</value>
      <webElementGuid>08c6acc7-c8da-472b-a3eb-a183fd727a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41120a61-4c4e-401d-858b-8719e5260c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;navbar navbar-default navbar-fixed-top style1  header-full-width light&quot;]/div[@class=&quot;nav-container&quot;]/div[@class=&quot;hazel_right_header_icons with-woocommerce-cart&quot;]/div[@class=&quot;menu-controls sliderbar-menu-controller menu-next-to-shopping-bag&quot;]/div[@class=&quot;font-icon custom-font-icon&quot;]/i[@class=&quot;ion-grid&quot;]</value>
      <webElementGuid>f8c66b3e-9bca-422b-b990-598856936a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div/div[2]/div[4]/div/i</value>
      <webElementGuid>b911b03d-e6c7-431d-b407-0cd5acdc00a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/i</value>
      <webElementGuid>0be393c1-ad89-4f96-8b0c-485c46ffdd1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
