<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CART_ion-search</name>
   <tag></tag>
   <elementGuidId>5d6ad89a-d22b-4107-bdfe-2d26b8c96b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div/div[2]/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ion-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d999018c-ae18-4e86-b157-4a93822f16b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-search</value>
      <webElementGuid>0bec8c11-89c9-491d-b563-9e9980968d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;navbar navbar-default navbar-fixed-top style1  header-full-width light&quot;]/div[@class=&quot;nav-container&quot;]/div[@class=&quot;hazel_right_header_icons with-woocommerce-cart&quot;]/div[@class=&quot;search_trigger next-to-shopping-bag&quot;]/a[1]/i[@class=&quot;ion-search&quot;]</value>
      <webElementGuid>2a560d6f-a529-4705-8d65-871867a2b3e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div/div[2]/div[2]/a/i</value>
      <webElementGuid>c0383987-9bed-4290-b990-4ea22590874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>3f9802af-d59c-4c14-8967-3e29cacc8c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
