<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CONTINUING EDUCATION_txtTarget</name>
   <tag></tag>
   <elementGuidId>c16a661a-acef-422a-8749-a0c23e713aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtTarget']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtTarget&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df67c220-67af-4178-8e9d-fb626adb1a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0bf4775-1ede-42d9-bffb-2a5baec2c87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value=' '</value>
      <webElementGuid>8349e49e-4b49-486f-8b48-96769580506a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  SEARCH COURSES</value>
      <webElementGuid>e269dc20-673d-49b4-9d55-c22e2cdfef6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTarget</value>
      <webElementGuid>aecc0008-29ed-42ab-9ba2-d571e2b70c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>09ada2c0-4554-4874-b423-e7912efa3da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_input_value srchField</value>
      <webElementGuid>83099bf1-5691-4e5b-ad27-ce187bd5a221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search results based on course number, course title and course description.</value>
      <webElementGuid>0ba177d6-ee74-40a5-a2de-e197360c7fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;srchBox&quot;)/input[@class=&quot;search_input_value srchField&quot;]</value>
      <webElementGuid>ef2ab42e-951d-4308-a2cd-af2acf4a8cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtTarget']</value>
      <webElementGuid>4c0146ba-5c44-4855-b170-e8f7c9949fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='srchBox']/input[2]</value>
      <webElementGuid>1bc37767-493e-489c-a722-046fd59cfec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a458c532-6ff5-4633-b0ac-10f1ad83299d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtTarget' and @title = 'Search results based on course number, course title and course description.']</value>
      <webElementGuid>86b856e4-44e0-4d13-b26d-33981ac7a70d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
