<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SH-Fundamentals-Logo</name>
   <tag></tag>
   <elementGuidId>cb05206c-13c6-4c3f-98d6-9e4e96a770f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Public Sector Safety and Health Fundamentals banner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='cert']/img)[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0744fba3-0bcf-4ff2-a68f-b882724108a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/wconnect/ace/webart/b/SH-Fundamentals-Logo.png</value>
      <webElementGuid>318c3f79-d147-4d20-8b70-b7bfbf0ed3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>eee9c7dc-b32e-4987-88c4-0ef71631b51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Public Sector Safety and Health Fundamentals banner</value>
      <webElementGuid>522bfb7b-de62-4ca2-b71b-81b700e21e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>e2ceed1f-339d-420b-a4d5-af85b7915166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>4b1d1349-e4ad-48bf-8900-333819c6b268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-md-12 col-sm-12 col-xs-12 text-center&quot;]/article[1]/p[@class=&quot;text-center&quot;]/a[@id=&quot;cert&quot;]/img[1]</value>
      <webElementGuid>4b4de866-54af-4632-8bef-e49a16314bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='cert']/img)[5]</value>
      <webElementGuid>293d99ee-fc14-46a6-934a-f624db3edd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Public Sector Safety and Health Fundamentals banner']</value>
      <webElementGuid>d5a1f048-7493-4a0b-bf3f-75bc2ba2de05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/article/p/a/img</value>
      <webElementGuid>1416bdd6-0fc7-4b6a-96fe-82369aea0ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/wconnect/ace/webart/b/SH-Fundamentals-Logo.png' and @alt = 'Public Sector Safety and Health Fundamentals banner']</value>
      <webElementGuid>f40a46dd-88c9-4412-88b4-63357425cfa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
