<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Order CFRs_mainimg</name>
   <tag></tag>
   <elementGuidId>78a0688f-d312-42ca-8cfb-0e2e886b902a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mainimg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div/div[4]/div[2]/div/div/article/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c8931214-1514-4710-9c45-48a162b3769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mainimg</value>
      <webElementGuid>f43bc870-b9ba-40d7-a661-d5bb8c0afe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cedwebfiles/catalogs/2024/2024 SH Fall Catalog_Thumnail.jpg</value>
      <webElementGuid>92b35fc9-d3a8-494f-b2ed-2e3f719fb1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3bf6a0f7-4244-4175-8669-26e3349b218b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Safety &amp; Health English Catalog cover</value>
      <webElementGuid>4b260263-8da7-494d-b5fa-4b2160f6df19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>f168611e-c5f6-4308-bba1-4af1a8d9fbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>1e2b281a-1b37-403c-a68c-bbfd47220ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-6 col-xs-12 text-center&quot;]/article[1]/a[1]/img[@class=&quot;mainimg&quot;]</value>
      <webElementGuid>19edeeea-03e8-472a-8971-a3957931073d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div[4]/div[2]/div/div/article/a/img</value>
      <webElementGuid>1c40e2c6-5908-4cc2-a3da-c7e6cb484692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Safety &amp; Health English Catalog cover']</value>
      <webElementGuid>83b9a5b2-009a-4b46-9dc0-ffd7501668a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/a/img</value>
      <webElementGuid>1ff5ee61-a9cf-42db-8867-1c09d0059341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/cedwebfiles/catalogs/2024/2024 SH Fall Catalog_Thumnail.jpg' and @alt = 'Safety &amp; Health English Catalog cover']</value>
      <webElementGuid>36b224ae-db10-4ace-9706-c4a1e7a2d4c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
